name: Convert pandoc
on: workflow_dispatch
jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: mkdir -p output
      - uses: docker://pandoc/extra:3.1
        with:
          args: document.md -o output/document.pdf --pdf-engine=xelatex  -V geometry=margin=1in
      - uses: docker://pandoc/extra:3.1
        with:
          args: document.md -o output/document.docx --highlight-style tango --reference-doc=.pandoc/reference.docx
      - uses: docker://pandoc/extra:3.1
        with:
          args: document.md -o output/document.pptx --highlight-style tango --reference-doc=.pandoc/reference.pptx
      - uses: actions/upload-artifact@v3
        with:
          path: output/*
