name: Convert pandoc
on: workflow_dispatch
jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: mkdir -p output
      - uses: docker://pandoc/extra:3.1
        with:
          args: document.md -o output/output.pdf --pdf-engine=xelatex  -V geometry=margin=1in
      - uses: actions/upload-artifact@v3
        with:
          name: output
          path: output
